export const CREATIVE_LISTING_SELECTORS = {
  username: [
    '#signin-email',
    '[data-testid="email"]',
    '[data-testid="username"]',
    'input[autocomplete="username"]',
    'input[type="email"]',
    'input[name="email"]',
    'input[name="username"]',
  ],
  password: [
    '#signin-password',
    '[data-testid="password"]',
    'input[autocomplete="current-password"]',
    'input[type="password"]',
    'input[name="password"]',
  ],
  loginSubmit: [
    '[data-testid="login-submit"]',
    'button[type="submit"]',
    'input[type="submit"]',
  ],
  authenticated: [
    'a[href="/dashboard"]',
    '[data-testid="listing-grid"]',
    '[data-testid="deal-grid"]',
    '[data-testid="account-menu"]',
    'a[href*="logout"]',
  ],
  listingContainer: [
    '[id^="deal-"]',
    '[data-testid="listing-grid"]',
    '[data-testid="deal-grid"]',
    '[data-testid="listing-card"]',
    '[data-testid="deal-card"]',
    '[data-listing-id]',
  ],
  emptyListings: [
    '[data-testid="empty-listings"]',
    '[data-testid="empty-deals"]',
    '[data-testid="no-results"]',
    '[role="status"][data-empty="true"]',
  ],
  listingLinks: [
    '[data-testid="listing-card"] a[href]',
    '[data-testid="deal-card"] a[href]',
    '[data-listing-id] a[href]',
    'a[href*="/listing/"]',
    'a[href*="/listings/"]',
    'a[href*="/deal/"]',
    'a[href*="/deals/"]',
  ],
  listingCards: '[id^="deal-"]',
  detailReady: 'h2:text-is("Listing Highlights"), h3:text-is("Listing Highlights"), [data-field], dl, [data-testid="listing-detail"]',
  renderedFieldLabels: 'p, span, label, h2, h3, div',
  publicNavigation: ['a[href="/auth"]', 'a[href^="/signup"]'],
  nextPage: [
    'button:text-is("Next")',
    '[data-testid="pagination-next"]',
    'a[rel="next"]',
    'button[aria-label="Next"]',
    'a[aria-label="Next"]',
    'button[aria-label="Next page"]',
    'a[aria-label="Next page"]',
  ],
  listingId: [
    '[data-listing-id]',
    '[data-deal-id]',
    '[data-testid="listing-id"]',
    '[data-testid="deal-id"]',
  ],
  accessBarrier: [
    'iframe[src*="captcha"]',
    '[data-testid="captcha"]',
    'input[autocomplete="one-time-code"]',
    'input[name*="otp" i]',
  ],
} as const;

export const FIELD_ALIASES: Readonly<Record<string, readonly string[]>> = {
  sourcePostedAt: ["posted date", "date posted", "listed", "created at", "listed on"],
  sourceStatus: ["listing status", "deal status", "status"],
  address: ["property address", "street address", "address"],
  city: ["city"],
  state: ["state"],
  zipCode: ["zip", "zip code", "zipcode", "postal code"],
  propertyType: ["property type", "type"],
  beds: ["bedrooms", "beds", "bed"],
  bathrooms: ["bathrooms", "baths", "bath"],
  fullBaths: ["full bathrooms", "full baths"],
  halfBaths: ["half bathrooms", "half baths"],
  squareFeet: ["square feet", "sq ft", "sqft", "property size"],
  yearBuilt: ["year built", "built"],
  purchasePrice: ["purchase price", "asking price", "price"],
  entryFee: ["entry fee", "cash to seller", "initial investment"],
  downPayment: ["down payment", "downpayment"],
  loanBalance: ["loan balance", "existing loan", "mortgage balance"],
  interestRate: ["interest rate", "rate"],
  piti: ["piti", "monthly piti", "PITI (Principal, Interest, Taxes, Insurance)"],
  monthlyPayment: ["monthly payment", "payment"],
  hoa: ["hoa", "hoa fee", "hoa dues", "HOA Monthly Fee"],
  financingType: ["financing type", "deal type", "financing"],
  occupancyStatus: ["occupancy", "occupancy status", "occupied"],
  description: ["description", "seller notes", "notes", "deal terms", "About this Listing"],
  balloonPayment: ["balloon payment", "balloon"],
  loanTerm: ["loan term", "term"],
  amortization: ["amortization", "amortization period"],
  lotSize: ["lot size"],
  pricePerSquareFoot: ["price/sqft"],
  parking: ["parking"],
  loanType: ["loan type"],
  earnestMoneyDeposit: ["earnest money deposit (emd)"],
  loanMaturityDate: ["loan maturity date"],
  expectedCloseOfEscrow: ["expected close of escrow"],
  optionFee: ["option fee"],
  optionSalePrice: ["option sale price"],
  optionTerm: ["option term", "option term (years)"],
  monthlyLeasePayment: ["monthly lease payment"],
};
